baseURL = 'https://sorendb.dk/'
languageCode = 'en-dk'
title = 'Søren Daugbjerg'
theme = 'hugo-coder'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
author = "Søren Daugbjerg"
info = ["Software Engineer && Digital Health"]
avatarURL = "avatar/soda.jpg"
colorScheme = "auto"
faviconSVG = "/favicon/favicon.ico"
favicon_32 = "/favicon/favicon-32x32.png"
favicon_16 = "/favicon/favicon-16x16.png"

# Menu Items
[[menu.main]]
name = "About"
weight = 1
url = "about/"
[[menu.main]]
name = "Blog"
weight = 2
url  = "blog/"

# Social Links
[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/sorendaugbjerg/"
[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin-in fa-2x"
weight = 2
url = "https://linkedin.com/in/sorendaugbjerg/"